### ISSUE TITLE
could help me run this code 

### ISSUE THREAD

**Issue by alialki** [jingz/CMMS#1]
I have no experience in ruby and i found this code and its exactly what i was looking for could you please help me run this app

**Comment by jingz** [comment]
http://cmms.herokuapp.com
this is demo site

user: admin@email.com
pass: 123123

for manager role
user: manager@email.com
pass: 123123

for staff role
user : staff@email.com

**Comment by islamRaafat** [comment]
how can i deploy it ???? and if u have ready link please provide it .......

**Comment by jingz** [comment]
first you have to install rails guide here http://rubyonrails.org/download/
second clone my project, 
config database connection at config/database.yml
then go into the root project directory and run
`rake db:migrate` # to initialize database schema
`ruby db:seed` # to initialize data 
then run the server by
`rails s`
for flexible of used and modification. learn Rails http://rubyonrails.org/documentation/

Demo site
http://cmms.heroku.com/
for admin role
user: admin@email.com
pass: 123123
for manager role
user: manager@email.com
pass: 123123
for staff role
user: staff@email.com
pass: 123123
